export const questionsData = {
    1: [
        { id: 1, text: "What is the capital of France?", options: [{ label: "Paris", value: 1 }, { label: "London", value: 2 }, { label: "Berlin", value: 3 }] },
        { id: 2, text: "Which river flows through Paris?", options: [{ label: "Seine", value: 1 }, { label: "Thames", value: 2 }, { label: "Danube", value: 3 }] },
        { id: 3, text: "What is the official language of France?", options: [{ label: "French", value: 1 }, { label: "English", value: 2 }, { label: "Spanish", value: 3 }] },
        { id: 4, text: "What is the currency used in France?", options: [{ label: "Euro", value: 1 }, { label: "Pound", value: 2 }, { label: "Dollar", value: 3 }] },
        { id: 5, text: "Which famous monument is located in Paris?", options: [{ label: "Eiffel Tower", value: 1 }, { label: "Statue of Liberty", value: 2 }, { label: "Big Ben", value: 3 }] },
        { id: 6, text: "Which French city is known for its wine?", options: [{ label: "Bordeaux", value: 1 }, { label: "Marseille", value: 2 }, { label: "Lyon", value: 3 }] },
        { id: 7, text: "Which famous museum is located in Paris?", options: [{ label: "Louvre", value: 1 }, { label: "British Museum", value: 2 }, { label: "Hermitage", value: 3 }] },
        { id: 8, text: "What is the French word for 'hello'?", options: [{ label: "Bonjour", value: 1 }, { label: "Hola", value: 2 }, { label: "Ciao", value: 3 }] },
        { id: 9, text: "Which French region is known for its champagne?", options: [{ label: "Champagne", value: 1 }, { label: "Burgundy", value: 2 }, { label: "Alsace", value: 3 }] },
        { id: 10, text: "Which French dish is made from snails?", options: [{ label: "Escargot", value: 1 }, { label: "Ratatouille", value: 2 }, { label: "Bouillabaisse", value: 3 }] },
    ],
    2: [
        { id: 1, text: "Which planet is known as the Red Planet?", options: [{ label: "Earth", value: 1 }, { label: "Mars", value: 2 }, { label: "Jupiter", value: 3 }] },
        { id: 2, text: "Which is the largest planet in our solar system?", options: [{ label: "Earth", value: 1 }, { label: "Jupiter", value: 2 }, { label: "Saturn", value: 3 }] },
        { id: 3, text: "Which planet is closest to the sun?", options: [{ label: "Mercury", value: 1 }, { label: "Venus", value: 2 }, { label: "Mars", value: 3 }] },
        { id: 4, text: "Which planet is known as the Earth's twin?", options: [{ label: "Venus", value: 1 }, { label: "Mars", value: 2 }, { label: "Mercury", value: 3 }] },
        { id: 5, text: "Which planet has rings?", options: [{ label: "Saturn", value: 1 }, { label: "Mars", value: 2 }, { label: "Earth", value: 3 }] },
        { id: 6, text: "Which planet is known for its Great Red Spot?", options: [{ label: "Jupiter", value: 1 }, { label: "Saturn", value: 2 }, { label: "Neptune", value: 3 }] },
        { id: 7, text: "Which planet is the farthest from the sun?", options: [{ label: "Neptune", value: 1 }, { label: "Uranus", value: 2 }, { label: "Pluto", value: 3 }] },
        { id: 8, text: "Which planet has the most moons?", options: [{ label: "Jupiter", value: 1 }, { label: "Saturn", value: 2 }, { label: "Mars", value: 3 }] },
        { id: 9, text: "Which planet is known for its extreme winds?", options: [{ label: "Neptune", value: 1 }, { label: "Jupiter", value: 2 }, { label: "Saturn", value: 3 }] },
        { id: 10, text: "Which planet has the shortest day?", options: [{ label: "Jupiter", value: 1 }, { label: "Earth", value: 2 }, { label: "Mars", value: 3 }] },
    ],
    3: [
        { id: 1, text: "Who wrote 'Romeo and Juliet'?", options: [{ label: "William Shakespeare", value: 1 }, { label: "Charles Dickens", value: 2 }, { label: "Mark Twain", value: 3 }] },
        { id: 2, text: "What is the capital of England?", options: [{ label: "London", value: 1 }, { label: "Paris", value: 2 }, { label: "Rome", value: 3 }] },
        { id: 3, text: "What is the national flower of England?", options: [{ label: "Rose", value: 1 }, { label: "Tulip", value: 2 }, { label: "Daffodil", value: 3 }] },
        { id: 4, text: "Who is the Queen of England?", options: [{ label: "Elizabeth II", value: 1 }, { label: "Victoria", value: 2 }, { label: "Anne", value: 3 }] },
        { id: 5, text: "What is the longest river in England?", options: [{ label: "Thames", value: 1 }, { label: "Severn", value: 2 }, { label: "Trent", value: 3 }] },
        { id: 6, text: "What is the highest mountain in England?", options: [{ label: "Scafell Pike", value: 1 }, { label: "Ben Nevis", value: 2 }, { label: "Snowdon", value: 3 }] },
        { id: 7, text: "Which English city is known for its football teams?", options: [{ label: "Manchester", value: 1 }, { label: "Liverpool", value: 2 }, { label: "London", value: 3 }] },
        { id: 8, text: "What is the oldest university in England?", options: [{ label: "Oxford", value: 1 }, { label: "Cambridge", value: 2 }, { label: "Durham", value: 3 }] },
        { id: 9, text: "What is the English word for 'hello'?", options: [{ label: "Hello", value: 1 }, { label: "Bonjour", value: 2 }, { label: "Hola", value: 3 }] },
        { id: 10, text: "Which English city is known for its port?", options: [{ label: "Liverpool", value: 1 }, { label: "Bristol", value: 2 }, { label: "Portsmouth", value: 3 }] },
    ],
    4: [
        { id: 1, text: "What is the capital of Italy?", options: [{ label: "Rome", value: 1 }, { label: "Milan", value: 2 }, { label: "Venice", value: 3 }] },
        { id: 2, text: "Which Italian city is known for its canals?", options: [{ label: "Venice", value: 1 }, { label: "Rome", value: 2 }, { label: "Florence", value: 3 }] },
        { id: 3, text: "What is the currency used in Italy?", options: [{ label: "Euro", value: 1 }, { label: "Lira", value: 2 }, { label: "Franc", value: 3 }] },
        { id: 4, text: "Which Italian city is famous for its fashion?", options: [{ label: "Milan", value: 1 }, { label: "Rome", value: 2 }, { label: "Turin", value: 3 }] },
        { id: 5, text: "What is the name of the famous Italian tower?", options: [{ label: "Leaning Tower of Pisa", value: 1 }, { label: "Eiffel Tower", value: 2 }, { label: "Big Ben", value: 3 }] },
        { id: 6, text: "Which Italian city is known for its pizza?", options: [{ label: "Naples", value: 1 }, { label: "Rome", value: 2 }, { label: "Milan", value: 3 }] },
        { id: 7, text: "Which Italian region is known for its wine?", options: [{ label: "Tuscany", value: 1 }, { label: "Sicily", value: 2 }, { label: "Piedmont", value: 3 }] },
        { id: 8, text: "Which Italian city is home to the Colosseum?", options: [{ label: "Rome", value: 1 }, { label: "Milan", value: 2 }, { label: "Naples", value: 3 }] },
        { id: 9, text: "What is the name of the famous Italian volcano?", options: [{ label: "Vesuvius", value: 1 }, { label: "Etna", value: 2 }, { label: "Stromboli", value: 3 }] },
        { id: 10, text: "Which Italian island is the largest?", options: [{ label: "Sicily", value: 1 }, { label: "Sardinia", value: 2 }, { label: "Corsica", value: 3 }] },
    ],
    5: [
        { id: 1, text: "What is the capital of Japan?", options: [{ label: "Tokyo", value: 1 }, { label: "Kyoto", value: 2 }, { label: "Osaka", value: 3 }] },
        { id: 2, text: "Which Japanese city is known for its temples?", options: [{ label: "Kyoto", value: 1 }, { label: "Tokyo", value: 2 }, { label: "Osaka", value: 3 }] },
        { id: 3, text: "What is the currency used in Japan?", options: [{ label: "Yen", value: 1 }, { label: "Won", value: 2 }, { label: "Dollar", value: 3 }] },
        { id: 4, text: "Which Japanese city is known for its cherry blossoms?", options: [{ label: "Kyoto", value: 1 }, { label: "Tokyo", value: 2 }, { label: "Sapporo", value: 3 }] },
        { id: 5, text: "What is the name of the famous Japanese mountain?", options: [{ label: "Mount Fuji", value: 1 }, { label: "Mount Everest", value: 2 }, { label: "Mount Kilimanjaro", value: 3 }] },
        { id: 6, text: "Which Japanese dish is made from raw fish?", options: [{ label: "Sushi", value: 1 }, { label: "Ramen", value: 2 }, { label: "Tempura", value: 3 }] },
        { id: 7, text: "Which Japanese city is known for its technology?", options: [{ label: "Tokyo", value: 1 }, { label: "Osaka", value: 2 }, { label: "Nagoya", value: 3 }] },
        { id: 8, text: "Which Japanese island is the largest?", options: [{ label: "Honshu", value: 1 }, { label: "Hokkaido", value: 2 }, { label: "Kyushu", value: 3 }] },
        { id: 9, text: "What is the name of the famous Japanese animation style?", options: [{ label: "Anime", value: 1 }, { label: "Manga", value: 2 }, { label: "Cartoon", value: 3 }] },
        { id: 10, text: "Which Japanese city hosted the 2020 Summer Olympics?", options: [{ label: "Tokyo", value: 1 }, { label: "Osaka", value: 2 }, { label: "Nagoya", value: 3 }] },
    ],
};
